correct tag comparisons for Role and Policy
aws-controllers-k8s/iam-controller pull request #41
Opened 2022-10-07 12:45 UTC by jaypipes

Lists of Tag structs for both the Role and Policy resources were causing
incorrect Delta differences to be detected when the order of the structs
was different. This brings in some code from the sfn-controller project
to properly ignore differences in only ordering for tags.

Issue aws-controllers-k8s/community#1503

Signed-off-by: Jay Pipes <jaypipes@gmail.com>

By submitting this pull request, I confirm that my contribution is made
under the terms of the Apache 2.0 license.

2022-10-07 16:22 UTC, A-Hilaly approved these changes

2022-10-07 16:25 UTC, A-Hilaly requested changes
I think two things are missing here. Changes to `sdk.go` after code generation, and ignore the original comparison logic for Tags field that was generated in `delta.go`

2022-10-07 16:38 UTC, jaypipes commented
> I think two things are missing here. Changes to `sdk.go` after code generation, and ignore the original comparison logic for Tags field that was generated in `delta.go`

doh. I changed generator.yaml and modded hooks.go and forgot to regen the controller :)

2022-10-07 16:39 UTC, jaypipes commented
@A-Hilaly OK, regen'd should be all set :)

2022-10-07 16:43 UTC, A-Hilaly reviewed
We should ignore this block In line 90 of `delta.go`:
```go
	if !reflect.DeepEqual(a.ko.Spec.Tags, b.ko.Spec.Tags) {
		delta.Add("Spec.Tags", a.ko.Spec.Tags, b.ko.Spec.Tags)
}
```
something like the following should fix it:
```yaml
fields:
  Tags:
     compare:
        is_ignored: true
```

2022-10-08 13:59 UTC, jaypipes commented
@A-Hilaly OK, all fixed up, thanks for your keen eyes!

2022-10-10 09:36 UTC, A-Hilaly commented
:+1:
/approve
/lgtm

2022-10-10 09:37 UTC, merged