Support `User` and `Role` permissions boundary updates
aws-controllers-k8s/iam-controller pull request #47
Opened 2022-11-07 23:17 UTC by A-Hilaly

Currently the update code path for `Users` and `Role` doesn't support
updates for permissionBoundary field. This patch adds the necessary
hooks and helper functions to help with that.

By submitting this pull request, I confirm that my contribution is made
under the terms of the Apache 2.0 license.

2022-11-07 23:18 UTC, A-Hilaly commented
/test all

2022-11-07 23:54 UTC, A-Hilaly commented
/test all

2022-11-08 00:03 UTC, A-Hilaly commented
/test all

2022-11-08 00:28 UTC, RedbackThomson requested changes

2022-11-08 00:28 UTC, RedbackThomson commented on pkg/resource/role/hooks.go
> +	rm.metrics.RecordAPICall("UPDATE", "putRolePermissionsBoundary", err)
```suggestion
rm.metrics.RecordAPICall("UPDATE", "PutRolePermissionsBoundary", err)
```

2022-11-08 00:28 UTC, RedbackThomson commented on pkg/resource/role/hooks.go
> +	rm.metrics.RecordAPICall("DELETE", "DeleteRolePermissionsBoundary", err)
```suggestion
rm.metrics.RecordAPICall("UPDATE", "DeleteRolePermissionsBoundary", err)
```

2022-11-08 00:28 UTC, RedbackThomson commented on pkg/resource/user/hooks.go
> +	rm.metrics.RecordAPICall("UPDATE", "putUserPermissionsBoundary", err)
```suggestion
rm.metrics.RecordAPICall("UPDATE", "PutUserPermissionsBoundary", err)
```

2022-11-08 00:28 UTC, RedbackThomson commented on pkg/resource/user/hooks.go
> +	rm.metrics.RecordAPICall("DELETE", "DeleteUserPermissionsBoundary", err)
```suggestion
rm.metrics.RecordAPICall("UPDATE", "DeleteUserPermissionsBoundary", err)
```

2022-11-08 00:37 UTC, jljaco commented on pkg/resource/role/hooks.go
> +// permission boundaries.
s/boundaries/boundary/

2022-11-08 00:37 UTC, jljaco commented on pkg/resource/role/hooks.go
> +// permission boundaries.
s/boundaries/boundary/

2022-11-08 00:37 UTC, jljaco commented on pkg/resource/user/hooks.go
> +	rm.metrics.RecordAPICall("UPDATE", "putUserPermissionsBoundary", err)
s/put/Put/

2022-11-08 15:38 UTC, jljaco commented
/lgtm

2022-11-08 15:39 UTC, jljaco approved these changes

2022-11-08 15:44 UTC, jaypipes commented on test/e2e/tests/test_role.py
> +
nit: whitespace.

2022-11-08 15:44 UTC, jaypipes commented
/lgtm

2022-11-08 15:45 UTC, merged